package persistence;

import logging.AuditEvent;
import logging.AuditEventType;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

class DatabaseAuditLoggerTest {
    private final DatabaseManager databaseManager = DatabaseManager.getInstance();

    @AfterEach
    void tearDown() {
        databaseManager.shutdown();
    }

    @Test
    void logEventDelegatesToAuditRepositoryWhenDatabaseIsInitialized() throws SQLException {
        AuditRepository repository = mock(AuditRepository.class);
        DatabaseAuditLogger logger = new DatabaseAuditLogger(() -> true, repository);
        AuditEvent event = new AuditEvent.Builder()
                .eventType(AuditEventType.ORDER_PLACED)
                .userId("BUYER1")
                .product("AAPL")
                .addData("quantity", 10)
                .build();

        logger.logEvent(event);

        verify(repository).save(event);
    }

    @Test
    void logEventDoesNotTouchRepositoryWhenDatabaseIsUnavailable() throws SQLException {
        AuditRepository repository = mock(AuditRepository.class);
        DatabaseAuditLogger logger = new DatabaseAuditLogger(() -> false, repository);
        AuditEvent event = new AuditEvent.Builder()
                .eventType(AuditEventType.SYSTEM_START)
                .build();

        logger.logEvent(event);

        verify(repository, never()).save(event);
    }

    @Test
    void logEventPersistsThroughJdbcRepositoryWhenH2DatabaseIsInitialized() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:audit_logger_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        databaseManager.initialize(dataSource);
        createAuditSchema();

        DatabaseAuditLogger logger = new DatabaseAuditLogger(databaseManager, new JdbcAuditRepository(databaseManager));
        AuditEvent event = new AuditEvent.Builder()
                .eventType(AuditEventType.ORDER_PLACED)
                .userId("BUYER1")
                .product("AAPL")
                .addData("quantity", 25)
                .build();
        event.setPreviousHash("0");
        event.setHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef");

        logger.logEvent(event);

        try (Connection conn = databaseManager.getConnection();
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM audit_log WHERE event_id = '"
                        + event.getEventId() + "'")) {
            rs.next();
            assertEquals(1, rs.getInt(1));
        }
    }

    private void createAuditSchema() throws SQLException {
        try (Connection conn = databaseManager.getConnection();
                Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE audit_log (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_id VARCHAR(36) NOT NULL UNIQUE,
                        event_type VARCHAR(50) NOT NULL,
                        timestamp TIMESTAMP NOT NULL,
                        user_id VARCHAR(50),
                        product VARCHAR(10),
                        data CLOB NOT NULL,
                        hash VARCHAR(64) NOT NULL,
                        prev_hash VARCHAR(64) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
        }
    }
}
