package exchange.model;

public enum RejectReason {
    INVALID_CLIENT,
    INVALID_SYMBOL,
    INVALID_ORDER_ID,
    INVALID_PRICE,
    INVALID_QUANTITY,
    INVALID_ORDER_TYPE,
    UNKNOWN_ORDER,
    RISK_KILL_SWITCH,
    RISK_NOTIONAL_LIMIT,
    RISK_POSITION_LIMIT,
    RISK_BUYING_POWER,
    RISK_PRICE_BAND,
    MARKET_HALTED,
    WOULD_SELF_TRADE,
    UNSUPPORTED_ORDER_TYPE
}
